version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.example
    restart: always

  backend:
    build: ../src
    restart: always
    volumes:
      - ../src:/app/
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: chat_backend
    depends_on:
      - db
    env_file:
      - .env.example

  nginx:
    image: nginx:1.19.3
    volumes:
      - backend_static:/backend_static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  backend_static:
  postgres_data: