# Generated by Django 4.2.11 on 2024-04-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='chat.chatsession', verbose_name='Сессия')),
            ],
        ),
    ]
